# Graphs

## Graph Implementation

for number of vertices `V` and number of edges `E`  


| Algorithm              | Adj List Time | Adj List Space | Adj Mat Time | Adj Mat Space |
| ---------------------- | ------------- | -------------- | ------------ | ------------- |
| **BFS**                | O(V + E)      | O(V)           | O(V²)        | O(V²)         |
| **DFS**                | O(V + E)      | O(V)           | O(V²)        | O(V²)         |
| **Topological Sort**   | O(V + E)      | O(V)           | O(V²)        | O(V²)         |
| **Longest Path (DAG)** | O(V + E)      | O(V)           | O(V²)        | O(V²)         |


In [98]:
import numpy as np
from collections import deque
import heapq

### __Undirected Graph__
![alt text](UndirectedGraph.png)
---

#### Adjacency Matrix

In [56]:
class AMGraphUndirected():
    def __init__(self):
        self.nodes = 5
        self.edges = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
        self.adj_matrix = np.zeros((self.nodes, self.nodes), dtype=int)

        for u, v in self.edges:
            self.adj_matrix[u][v] = 1
            self.adj_matrix[v][u] = 1

    def display(self):
        print("Adjacency Matrix:")
        print(self.adj_matrix)

    def add_edge(self, u, v):
        if u < self.adj_matrix.shape[0] and v < self.adj_matrix.shape[1]:
            self.adj_matrix[u][v] = 1
            self.adj_matrix[v][u] = 1
        else:
            print("Invalid edge")

    def remove_edge(self, u, v):
        if u < self.adj_matrix.shape[0] and v < self.adj_matrix.shape[1]:
            self.adj_matrix[u][v] = 0
            self.adj_matrix[v][u] = 0
        else:
            print("Invalid edge")

    def BFS(self, start):
        queue = deque([start])
        visited = []
        visited.append(start)

        while queue:
            node = queue.popleft()
            for neighbor in range(self.nodes):
                if self.adj_matrix[node][neighbor] == 1 and neighbor not in visited:
                    visited.append(neighbor)
                    queue.append(neighbor) 

        return visited 

    def DFS(self, start):
        stack = [start]
        visited = []

        while stack:
            node = stack.pop()
            if node not in visited:
                visited.append(node)
                for neighbor in range(self.nodes - 1, -1, -1):
                    if self.adj_matrix[node][neighbor] == 1 and neighbor not in visited:
                        stack.append(neighbor)

        return visited

In [61]:
AMgraphU = AMGraphUndirected()
AMgraphU.display()
print("BFS starting from node 3:", AMgraphU.BFS(3))
print("DFS starting from node 3:", AMgraphU.DFS(3))

Adjacency Matrix:
[[0 1 1 0 0]
 [1 0 0 1 1]
 [1 0 0 1 1]
 [0 1 1 0 1]
 [0 1 1 1 0]]
BFS starting from node 3: [3, 1, 2, 4, 0]
DFS starting from node 3: [3, 1, 0, 2, 4]


#### Adjacency List

In [54]:
class ALGraphUndirected():
    def __init__(self):
        self.nodes = 5
        self.edges = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
        self.adj_list = {i: [] for i in range(self.nodes)}

        for u, v in self.edges:
            self.adj_list[u].append(v)
            self.adj_list[v].append(u)

    def display(self):
        print("Adjacency List:")
        for node in self.adj_list:
            print(f"{node}: {self.adj_list[node]}")

    def add_edge(self, u, v):
        if u < self.nodes and v < self.nodes:
            self.adj_list[u].append(v)
            self.adj_list[v].append(u)
        else:
            print("Invalid edge")

    def remove_edge(self, u, v):
        if u < self.nodes and v < self.nodes:
            self.adj_list[u].remove(v)
            self.adj_list[v].remove(u)
        else:
            print("Invalid edge")

    def BFS(self, start):
        queue = deque([start])
        visited = []
        visited.append(start)

        while queue:
            node = queue.popleft()
            for neighbor in self.adj_list[node]:
                if neighbor not in visited:
                    visited.append(neighbor)
                    queue.append(neighbor)

        return visited
    
    def DFS(self, start):
        stack = [start]
        visited = []

        while stack:
            node = stack.pop()
            if node not in visited:
                visited.append(node)
                for neighbor in reversed(self.adj_list[node]):
                    if neighbor not in visited:
                        stack.append(neighbor)

        return visited

In [55]:
ALgraphU = ALGraphUndirected()
ALgraphU.display()
print("BFS starting from node 3:", ALgraphU.BFS(3))
print("DFS starting from node 3:", ALgraphU.DFS(3))

Adjacency List:
0: [1, 2]
1: [0, 3, 4]
2: [0, 4, 3]
3: [1, 2, 4]
4: [1, 2, 3]
BFS starting from node 3: [3, 1, 2, 4, 0]
DFS starting from node 3: [3, 1, 0, 2, 4]


### __Directed Graph__
![alt text](DirectedGraph.png)
___

#### Adjacency Matrix

In [52]:
class AMGraphDirected():
    def __init__(self):
        self.nodes = 5
        self.edges = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
        self.adj_matrix = np.zeros((self.nodes, self.nodes), dtype=int)

        for u, v in self.edges:
            self.adj_matrix[u][v] = 1

    def display(self):
        print("Adjacency Matrix (Directed):")
        print(self.adj_matrix)

    def add_edge(self, u, v):
        if u < self.adj_matrix.shape[0] and v < self.adj_matrix.shape[1]:
            self.adj_matrix[u][v] = 1
        else:
            print("Invalid edge")

    def remove_edge(self, u, v):
        if u < self.adj_matrix.shape[0] and v < self.adj_matrix.shape[1]:
            self.adj_matrix[u][v] = 0
        else:
            print("Invalid edge")

    def BFS(self, start):
        queue = deque([start])
        visited = []
        visited.append(start)

        while queue:
            node = queue.popleft()
            for neighbor in range(self.nodes):
                if self.adj_matrix[node][neighbor] == 1 and neighbor not in visited:
                    visited.append(neighbor)
                    queue.append(neighbor)

        return visited
    
    def DFS(self, start):
        stack = [start]
        visited = []

        while stack:
            node = stack.pop()
            if node not in visited:
                visited.append(node)
                for neighbor in range(self.nodes - 1, -1, -1):
                    if self.adj_matrix[node][neighbor] == 1 and neighbor not in visited:
                        stack.append(neighbor)

        return visited

In [59]:
AMGaphD = AMGraphDirected()
AMGaphD.display()
print("BFS starting from node 0:", AMGaphD.BFS(0))
print("DFS starting from node 0:", AMGaphD.DFS(0))

Adjacency Matrix (Directed):
[[0 1 1 0 0]
 [0 0 0 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
BFS starting from node 0: [0, 1, 2, 3, 4]
DFS starting from node 0: [0, 1, 3, 4, 2]


#### Adjacency List

In [63]:
class ALGraphDirected():
    def __init__(self):
        self.nodes = 5
        self.edges = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
        self.adj_list = {i: [] for i in range(self.nodes)}

        for u, v in self.edges:
            self.adj_list[u].append(v)

    def display(self):
        print("Adjacency List (Directed):")
        for node in self.adj_list:
            print(f"{node}: {self.adj_list[node]}")

    def add_edge(self, u, v):
        if u < self.nodes and v < self.nodes:
            self.adj_list[u].append(v)
        else:
            print("Invalid edge")

    def remove_edge(self, u, v):
        if u < self.nodes and v < self.nodes:
            self.adj_list[u].remove(v)
        else:
            print("Invalid edge")

    def BFS(self, start):
        queue = deque([start])
        visited = []
        visited.append(start)

        while queue:
            node = queue.popleft()
            for neighbor in self.adj_list[node]:
                if neighbor not in visited:
                    visited.append(neighbor)
                    queue.append(neighbor)

        return visited
    
    def DFS(self, start):
        stack = [start]
        visited = []

        while stack:
            node = stack.pop()
            if node not in visited:
                visited.append(node)
                for neighbor in reversed(self.adj_list[node]):
                    if neighbor not in visited:
                        stack.append(neighbor)

        return visited

In [64]:
ALgraphD = ALGraphDirected()
ALgraphD.display()
print("BFS starting from node 0:", ALgraphD.BFS(0))
print("DFS starting from node 0:", ALgraphD.DFS(0))

Adjacency List (Directed):
0: [1, 2]
1: [3, 4]
2: [4, 3]
3: [4]
4: []
BFS starting from node 0: [0, 1, 2, 3, 4]
DFS starting from node 0: [0, 1, 3, 4, 2]


### __Directed Acyclic Graph(DAG)__
![alt text](DAG.png)
___

In [72]:
class DAG():
    def __init__(self):
        self.AList = {0: [2, 3, 4], 1: [2, 7], 2: [5], 3: [5, 7], 4: [7], 5: [6], 6: [7], 7: []}

    def display(self):
        print("Adjacency List (DAG):")
        for node in self.AList:
            print(f"{node}: {self.AList[node]}")

    def TopologicalSort(self):
        in_degree = {u: 0 for u in self.AList}
        for u in self.AList:
            for v in self.AList[u]:
                in_degree[v] += 1

        # Collect nodes with in-degree 0
        queue = deque([u for u in self.AList if in_degree[u] == 0])
        topo_order = []

        while queue:
            u = queue.popleft()
            topo_order.append(u)
            for v in self.AList[u]:
                in_degree[v] -= 1
                if in_degree[v] == 0:
                    queue.append(v)

        if len(topo_order) != len(self.AList):
            print("Graph has a cycle!")
            return []
        
        return topo_order
    

    def LongestPath(self):
        topo_order = self.TopologicalSort()
        if not topo_order:
            return []

        dist = {u: 0 for u in self.AList}
        dist[topo_order[0]] = 0

        for u in topo_order:
            for v in self.AList[u]:
                if dist[v] < dist[u] + 1:
                    dist[v] = dist[u] + 1

        return dist

In [73]:
dag = DAG()
dag.display()
topo_order = dag.TopologicalSort()
if topo_order:  
    print("Topological Sort Order:", topo_order)

longest_path = dag.LongestPath()
if longest_path:    
    print("Longest Path Distances from Start Node:", longest_path)

Adjacency List (DAG):
0: [2, 3, 4]
1: [2, 7]
2: [5]
3: [5, 7]
4: [7]
5: [6]
6: [7]
7: []
Topological Sort Order: [0, 1, 3, 4, 2, 5, 6, 7]
Longest Path Distances from Start Node: {0: 0, 1: 0, 2: 1, 3: 1, 4: 1, 5: 2, 6: 3, 7: 4}


### __Weighted Graph__
![alt text](WeightedDirectedGraph.png)
___



| Algorithm          | Adj List Time    | Adj List Space | Adj Mat Time | Adj Mat Space |
| ------------------ | ---------------- | -------------- | ------------ | ------------- |
| **Dijkstra**       | O((V + E) log V) | O(V + E)       | O(V²)        | O(V²)         |
| **Bellman-Ford**   | O(V × E)         | O(V + E)       | O(V³)        | O(V²)         |
| **Floyd-Warshall** | ❌ Not suitable   | ❌              | O(V³)        | O(V²)      |


In [97]:
class WieghtedDirectedGraph():
    def __init__(self):
        self.nodes = 7
        self.edges = [(0,1,10),(0,2,80),(1,2,6),(1,4,20),(2,3,70),(4,5,50),(4,6,5),(5,6,10)]

        self.adj_matrix = np.full((self.nodes, self.nodes), np.inf)
        np.fill_diagonal(self.adj_matrix, 0)

        for u, v, w in self.edges:
            self.adj_matrix[u][v] = w

    def display(self):
        print("Weighted Adjacency Matrix:")
        with np.printoptions(precision=0, suppress=True):
            print(np.where(self.adj_matrix == np.inf, ' ∞ ', self.adj_matrix))


    def add_edge(self, u, v, weight):
        if u < self.adj_matrix.shape[0] and v < self.adj_matrix.shape[1]:
            self.adj_matrix[u][v] = weight
        else:
            print("Invalid edge")

    def remove_edge(self, u, v):
        if u < self.adj_matrix.shape[0] and v < self.adj_matrix.shape[1]:
            self.adj_matrix[u][v] = np.inf
        else:
            print("Invalid edge")

    def Dijkstra(self, start):
        dist = {i: float('inf') for i in range(self.nodes)}
        dist[start] = 0
        visited = set()

        for _ in range(self.nodes):
            min_node = None
            for node in range(self.nodes):
                if node not in visited and (min_node is None or dist[node] < dist[min_node]):
                    min_node = node

            if min_node is None:
                break

            visited.add(min_node)

            for neighbor in range(self.nodes):
                if self.adj_matrix[min_node][neighbor] > 0:
                    new_dist = dist[min_node] + self.adj_matrix[min_node][neighbor]
                    if new_dist < dist[neighbor]:
                        dist[neighbor] = new_dist

        for dis in dist:
            if dist[dis] != float('inf'):
                dist[dis] = int(dist[dis])
                
        return dist
    

    def BellmanFord(self, start):
        dist = {i: float('inf') for i in range(self.nodes)}
        dist[start] = 0

        for _ in range(self.nodes - 1):
            for u, v, w in self.edges:
                if dist[u] != float('inf') and dist[u] + w < dist[v]:
                    dist[v] = dist[u] + w

        # Check for negative weight cycles
        for u, v, w in self.edges:
            if dist[u] != float('inf') and dist[u] + w < dist[v]:
                print("Graph contains a negative weight cycle!")
                return None

        return dist
    
    def FloydWarshall(self):
        dist = np.copy(self.adj_matrix)
        for k in range(self.nodes):
            for i in range(self.nodes):
                for j in range(self.nodes):
                    if dist[i][j] > dist[i][k] + dist[k][j]:
                        dist[i][j] = dist[i][k] + dist[k][j]

        return dist

In [ ]:
WDGraph = WieghtedDirectedGraph()
WDGraph.display()
print("\nDijkstra's shortest path from node 0:", WDGraph.Dijkstra(0))
print("\nBellman-Ford shortest path from node 0:", WDGraph.BellmanFord(0))
print("\nFloyd-Warshall All-Pairs Shortest Paths: \n" , WDGraph.FloydWarshall())

Weighted Adjacency Matrix:
[['0.0' '10.0' '80.0' ' ∞ ' ' ∞ ' ' ∞ ' ' ∞ ']
 [' ∞ ' '0.0' '6.0' ' ∞ ' '20.0' ' ∞ ' ' ∞ ']
 [' ∞ ' ' ∞ ' '0.0' '70.0' ' ∞ ' ' ∞ ' ' ∞ ']
 [' ∞ ' ' ∞ ' ' ∞ ' '0.0' ' ∞ ' ' ∞ ' ' ∞ ']
 [' ∞ ' ' ∞ ' ' ∞ ' ' ∞ ' '0.0' '50.0' '5.0']
 [' ∞ ' ' ∞ ' ' ∞ ' ' ∞ ' ' ∞ ' '0.0' '10.0']
 [' ∞ ' ' ∞ ' ' ∞ ' ' ∞ ' ' ∞ ' ' ∞ ' '0.0']]

Dijkstra's shortest path from node 0: {0: 0, 1: 10, 2: 16, 3: 86, 4: 30, 5: 80, 6: 35}

Bellman-Ford shortest path from node 0: {0: 0, 1: 10, 2: 16, 3: 86, 4: 30, 5: 80, 6: 35}

Floyd-Warshall All-Pairs Shortest Paths: 
 [[ 0. 10. 16. 86. 30. 80. 35.]
 [inf  0.  6. 76. 20. 70. 25.]
 [inf inf  0. 70. inf inf inf]
 [inf inf inf  0. inf inf inf]
 [inf inf inf inf  0. 50.  5.]
 [inf inf inf inf inf  0. 10.]
 [inf inf inf inf inf inf  0.]]


### __Minimum Spanning Tree__
![alt text](WeightedUndirectedGraph.png)
___  


| Algorithm     | Adj List Time    | Adj List Space | Adj Matrix Time | Adj Matrix Space |
| ------------- | ---------------- | -------------- | --------------- | ---------------- |
| **Prim’s**    | O((V + E) log V) | O(V + E)       | O(V²)           | O(V²)            |
| **Kruskal’s** | O(E log E)       | O(E + V)       | O(V² log V)     | O(V²)            |


In [106]:
class WieghtedUndirectedGraph():
    def __init__(self):
        self.nodes = 5
        self.edges = [(0,1,10),(0,3,18),(1,2,20),(1,3,6),(2,4,8),(3,4,70)]

        self.adj_list = {i: [] for i in range(self.nodes)}

        for u, v, w in self.edges:
            self.adj_list[u].append((v, w))
            self.adj_list[v].append((u, w))
        
    def display(self):
        print("Weighted Adjacency List:")
        for node in self.adj_list:
            print(f"{node}: {self.adj_list[node]}")

    def add_edge(self, u, v, weight):
        if u < self.nodes and v < self.nodes:
            self.adj_list[u].append((v, weight))
            self.adj_list[v].append((u, weight))
        else:
            print("Invalid edge")

    def remove_edge(self, u, v):
        if u < self.nodes and v < self.nodes:
            self.adj_list[u] = [(x, w) for x, w in self.adj_list[u] if x != v]
            self.adj_list[v] = [(x, w) for x, w in self.adj_list[v] if x != u]
        else:
            print("Invalid edge")

    def Prim(self):
        visited = set()
        mst_edges = []
        min_heap = [(0, 0, -1)]
        total_weight = 0
        while min_heap:
            weight, u, parent = heapq.heappop(min_heap)

            if u in visited:
                continue

            visited.add(u)
            if parent != -1:
                mst_edges.append((parent, u))

            total_weight += weight
            
            for v, w in self.adj_list[u]:
                if v not in visited:
                    heapq.heappush(min_heap, (w, v, u))
        
        return mst_edges, total_weight
    
    def Kruskal(self):
        parent = list(range(self.nodes))
        rank = [0] * self.nodes
        total_weight = 0

        def find(u):
            if parent[u] != u:
                parent[u] = find(parent[u])
            return parent[u]

        def union(u, v):
            root_u = find(u)
            root_v = find(v)
            if root_u != root_v:
                if rank[root_u] > rank[root_v]:
                    parent[root_v] = root_u
                elif rank[root_u] < rank[root_v]:
                    parent[root_u] = root_v
                else:
                    parent[root_v] = root_u
                    rank[root_u] += 1

        edges = sorted(self.edges, key=lambda x: x[2])
        mst_edges = []

        for u, v, w in edges:
            if find(u) != find(v):
                union(u, v)
                mst_edges.append((u, v))
                total_weight += w

        return mst_edges, total_weight

In [107]:
WUGraph = WieghtedUndirectedGraph()
WUGraph.display()
print("\nPrim's Minimum Spanning Tree:", WUGraph.Prim())
print("\nKruskal's Minimum Spanning Tree:", WUGraph.Kruskal())

Weighted Adjacency List:
0: [(1, 10), (3, 18)]
1: [(0, 10), (2, 20), (3, 6)]
2: [(1, 20), (4, 8)]
3: [(0, 18), (1, 6), (4, 70)]
4: [(2, 8), (3, 70)]

Prim's Minimum Spanning Tree: ([(0, 1), (1, 3), (1, 2), (2, 4)], 44)

Kruskal's Minimum Spanning Tree: ([(1, 3), (2, 4), (0, 1), (1, 2)], 44)
